### ISSUE TITLE
Getting the same embedding for words with different contextual meaning

### ISSUE THREAD

**Issue by lvbeltranb** [imgarylai/bert-embedding#14]
Hello, I was testing the library, I understand that BERT outputs different embeddings for same words in different contexts, however, I'm getting the same embedding for the same words in different sentences with different contextual meanings. Am I doing it wrong? or why I'm having these results. For example, if I do this with the sentences = ['bank holidays are state specific','the national bank of europe'], the word bank is having the exact same embedding,. Other sample, sentences = ['I went to see the school of fishes', 'I went to my school'], the word 'school' again have the exact same embedding. Can you please help me with this doubt? because, I'm using it for many samples, and for same words, I'm getting the same embedding...

sentences = ['I went to my school','I went to see the school of fishes']                                                                                                                                     
sentences = [sentence.split(' ') for sentence in sentences]                                                                                                                                                  
In [6]: sentences                                                                                                                                                                                             
[['I', 'went', 'to', 'my', 'school'],
 ['I', 'went', 'to', 'see', 'the', 'school', 'of', 'fishes']]
e1= bert.embedding(sentences[0])                                                                                                                                                                             
e2= bert.embedding(sentences[1])
(e1[4][1][0] == e2[5][1][0]).all()                                                                                                                                                                          
Out[14]: True
Thanks very much!

**Comment by imgarylai** [comment]
I checked it again. Those two 'school' didn't get same embedding. Let me give you my implementation. 

Your implementation looks okay, but there is a thing different from mine. 
If you want to get embedding from multiple sentences, you can pass all sentences together. 

```python
sentences = ['I went to my school', 'I went to see the school of fishes']
bert_embedding = BertEmbedding()
result = bert_embedding(sentences)
```

You can now get embedding from each sentences like:

```python
first_sentence, second_sentence = result[0], result[1]
first_sentence[0]
> ['i', 'went', 'to', 'my', 'school']
second_sentence[0]
> ['i', 'went', 'to', 'see', 'the', 'school', 'of', 'fishes']
```

I check `i` first. Same word but yes, there are different. 

```python
(first_sentence[1][0] == second_sentence[1][0]).all()
> False
first_sentence[1][0][:5]
> array([ 0.16621551, -0.2211662 ,  0.00395185,  0.39004615, -0.07105252],
      dtype=float32)
second_sentence[1][0][:5]
> array([ 0.29869875, -0.3642278 ,  0.18888001,  0.24514227, -0.0537507 ],
      dtype=float32)
```

And 'school'. There are still different. 

```python
first_sentence[0][4]
> 'school'
second_sentence[0][5]
> 'school'
(first_sentence[1][4] == second_sentence[1][5]).all()
> False
first_sentence[1][4][:5]
> array([-0.07660088, -0.13872012, -0.770428  , -0.41587162,  0.48860264],
      dtype=float32)
second_sentence[1][5][:5]
> array([ 0.6472298 ,  0.36400783, -0.16234158,  0.19270225,  0.0860156 ],
      dtype=float32)
```

**Comment by lvbeltranb** [comment]
Ok, thanks for your answer, the problem I'm having then, is when I create the instance of Bert, 
if I run this:
sentences = ['I went to my school', 'I went to see the school of fishes']
bert_embedding = BertEmbedding()
result = bert_embedding(sentences)
I got the error:
TypeError: 'BertEmbedding' object is not callable

So, I thought I had to call bert_embedding.embedding(sentences), and that way, it works but I got the same embeddings... So, I don't know what I'm doing wrong...

Thanks very much!

**Comment by imgarylai** [comment]
Please update this package!

```
pip install --upgrade bert-embedding
```

**Comment by lvbeltranb** [comment]
Thanks very much!
