### ISSUE TITLE
Get embedding from Biobert pre-trained weights

### ISSUE THREAD

**Issue by pyturn** [imgarylai/bert-embedding#16]
Hi, I have these Biobert pretrained weights available. https://github.com/naver/biobert-pretrained . Now how can I use this code to get the embeddings for particular word or sentence ?

**Comment by imgarylai** [comment]
Hi @pyturn, this project is using the API from gluonnlp. So, currently, it's not possible to load your own pre-trained. However, I believe many people have the same problem as you. 

Would you be able to start an issue on gluonnlp page? https://github.com/dmlc/gluon-nlp/issues

Thank you

**Comment by pyturn** [comment]
> Hi @pyturn, this project is using the API from gluonnlp. So, currently, it's not possible to load your own pre-trained. However, I believe many people have the same problem as you.
> 
> Would you be able to start an issue on gluonnlp page? https://github.com/dmlc/gluon-nlp/issues
> 
> Thank you

Thanks for responding back. I figured it out how to get embeddings from pretrained model.

**Comment by bikashg** [comment]
> > Hi @pyturn, this project is using the API from gluonnlp. So, currently, it's not possible to load your own pre-trained. However, I believe many people have the same problem as you.
> > Would you be able to start an issue on gluonnlp page? https://github.com/dmlc/gluon-nlp/issues
> > Thank you
> 
> Thanks for responding back. I figured it out how to get embeddings from pretrained model.

Hi @pyturn, How did you manage to get that? Please let us know.

**Comment by bikashg** [comment]
To those who are looking for the same answer, this page has the solution :)

[https://github.com/dmlc/gluon-nlp/issues/843](url)
