### ISSUE TITLE
'BERTTokenizer'

### ISSUE THREAD

**Issue by Kapoor9597** [imgarylai/bert-embedding#3]
Hey,

I want to experiment with BERT embeddings for a classifcation problem but when I try to import the bert module I am getting this error:

```
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-89-a4e843f9f02c> in <module>()
----> 1 from bert_embedding.bert import BertEmbedding

~\AppData\Roaming\Python\Python36\site-packages\bert_embedding\__init__.py in <module>()
      1 __author__ = "Gary Lai"
      2 
----> 3 from .bert import BertEmbedding

~\AppData\Roaming\Python\Python36\site-packages\bert_embedding\bert.py in <module>()
      5 import gluonnlp
      6 import mxnet as mx
----> 7 from gluonnlp.data import BERTTokenizer, BERTSentenceTransform
      8 from mxnet.gluon.data import DataLoader
      9 

ImportError: cannot import name 'BERTTokenizer'
```

Anyone please suggest how can I handle this? I have pip installed the bert module using:

`pip install --user bert-embedding`

**Comment by imgarylai** [comment]
This package relies on the latest gluonnlp api. 

Please install the latest gluonnlp package by
```
pip install https://github.com/dmlc/gluon-nlp/tarball/master
```

Ref: https://github.com/imgarylai/bert-embedding#install

**Comment by Kapoor9597** [comment]
Thanks :) It worked 👍

**Comment by jinnythomas** [comment]
Hi I am facing the below issues

!pip install -e git+https://github.com/negedng/bert-embedding#egg=bert_embedding
from bert_embedding import BertEmbedding
bert_E = BertEmbedding()

ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-24-4194e4005aff> in <module>()
      1 get_ipython().system('pip install -e git+https://github.com/negedng/bert-embedding#egg=bert_embedding')
----> 2 from bert_embedding import BertEmbedding
      3 bert_E = BertEmbedding()

ModuleNotFoundError: No module named 'bert_embedding'

**Comment by jinnythomas** [comment]
I have also tried pip install bert-embedding

Same error coming
