### ISSUE TITLE
How is the sentence embedding generated?

### ISSUE THREAD

**Issue by cmxcn** [imgarylai/bert-embedding#4]
Hi,  I checked the codes but I cannot find the logic how the sentence embedding is generated, is it from one layer output+pooling or something else? could you please explain a little bit about it? Thanks.

**Comment by imgarylai** [comment]
The embedding is from the last layer of the `BERTModel`.
The full implementation is on gluonnlp: https://github.com/dmlc/gluon-nlp/blob/master/src/gluonnlp/model/bert.py

**Comment by cmxcn** [comment]
I see, thanks. I'll take a look at your reference.

**Comment by TiewKH** [comment]
Hi, I have the same question and had looked at gluonnlp's code but still can't figure out where the sentence embedding comes from. 
From my understanding, isn't the last layer of BERT supposed to be word embeddings? There seems to be a pooled_output but I'm not sure. Thanks

**Comment by imgarylai** [comment]
@cmxcn @TiewKH 
Sorry, I was wrong. I didn't check it very carefully to make you guys confused. Yes, the output was not sentence embedding. It was a `pooled_out` representing a tensor of pooled representation of the first tokens. 

The output has been removed. Thanks!
