### ISSUE TITLE
an unexpected keyword argument 'filter_spec_tokens'

### ISSUE THREAD

**Issue by sinaahmadi** [imgarylai/bert-embedding#40]
When trying to run the following:

```
bertEmb = BertEmbedding()
embs = bertEmb([sentence], filter_spec_tokens=False)
```

I get the following error:

```
TypeError: __call__() got an unexpected keyword argument 'filter_spec_tokens'
```

I am running `Python 3.7.3` on macOS Catalina (10.15.4). 

Can somebody help me fix the problem?

**Comment by JustCunn** [comment]
I know this is very late, so it may not be useful anymore. However, I got the same issue, and it's down to the `pip` version of the package not being up to date. Perhaps build by using `git clone...` or find where the package is installed and edit `bert.py` yourself.
