### ISSUE TITLE
TypeError: 'BertEmbedding' object is not callable

### ISSUE THREAD

**Issue by rameshjesswani** [imgarylai/bert-embedding#8]
Hello, 
I have tried sample  [example](https://github.com/imgarylai/bert-embedding#usage) in README, but i am getting this error:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: 'BertEmbedding' object is not callable

```

gluonnlp version: ```0.5.1```
mxnet version: ```1.3.0```
python version: ```3.6.7```

Could anyone help me this?
Thanks

**Comment by imgarylai** [comment]
@rameshjesswani 

Few things would you help me to check? 
1. Do you install the latest version of `bert-embedding`? The latest version is `0.1.4`
2. Would you be able to install `gluonnlp` from its GitHub source by:
```
pip install https://github.com/dmlc/gluon-nlp/tarball/master
```
The reason why you need to install gluonnlp from source is that this project requires the latest API from gluonnlp. (We're going to release it soon!) So, before it is released, please install it from the source. 

If you still encounter any problem, please let me know. I would try to help you figure it out. 
Thanks

**Comment by rameshjesswani** [comment]
@imgarylai  Thanks for your response. 
I have checked the version of ```bert-embedding``` , it is ```0.1.4```
and i have also installed ```gluonnlp``` from Github source. still i am facing same issue.

**Comment by imgarylai** [comment]
Would you be able to create an minimal example for me? because I can't replicate this issue. 
I have tested on a clean machine with new virturalenv again and it works fine.

**Comment by rameshjesswani** [comment]
I again created new ```python3``` environment. but still same issue persists. could you please check now? 

```
>>> from bert_embedding import BertEmbedding
>>> bert_abstract = """We introduce a new language representation model called BERT, which stands for Bidirectional Encoder Representations from Transformers.
...  Unlike recent language representation models, BERT is designed to pre-train deep bidirectional representations by jointly conditioning on both left and right context in all layers.
...  As a result, the pre-trained BERT representations can be fine-tuned with just one additional output layer to create state-of-the-art models for a wide range of tasks, such as question answering and language inference, without substantial task-specific architecture modifications. 
... BERT is conceptually simple and empirically powerful. 
... It obtains new state-of-the-art results on eleven natural language processing tasks, including pushing the GLUE benchmark to 80.4% (7.6% absolute improvement), MultiNLI accuracy to 86.7 (5.6% absolute improvement) and the SQuAD v1.1 question answering Test F1 to 93.2 (1.5% absolute improvement), outperforming human performance by 2.0%."""
>>> sentences = bert_abstract.split('\n')
>>> bert_embedding = BertEmbedding()
/home/ramesh/virtualenvs/bert_embedding_repo/lib/python3.6/site-packages/gluonnlp/model/block.py:113: UserWarning: `erf` operator support is not found. Please consider upgrading to mxnet >= 1.4
  warnings.warn('`erf` operator support is not found. '
>>> result = bert_embedding(sentences)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: 'BertEmbedding' object is not callable


```

**Comment by imgarylai** [comment]
@rameshjesswani I forgot that `__call__` was implemented in `0.1.5`. 

I created a `0.1.5` release! Once it has been uploaded to pypi, please upgrade your bert_embedding to the latest version. sorry for that.

**Comment by rameshjesswani** [comment]
thanks it is working now :)

**Comment by imgarylai** [comment]
@rameshjesswani The dependencies has been updated. 
You can use this package by just running `pip install bert-embedding`!
